# Generated by Django 5.0.6 on 2024-06-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_book_id_alter_category_id_alter_review_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slideimg',
        ),
    ]
