# Generated by Django 5.0.6 on 2024-06-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_slider_slideimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
