# Generated by Django 5.0.6 on 2024-06-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
