# Generated by Django 5.0.6 on 2024-06-24 10:55

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(validators=[order.models.validate_zip_code]),
        ),
    ]
